{{- if .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  labels:
    {{- include "pcaims-deployment.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"ghcr.io":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.ghcr.username .Values.ghcr.token (printf "%s:%s" .Values.ghcr.username .Values.ghcr.token | b64enc) | b64enc }}
{{- end }}