[project]
name = "product-catalog-and-inventory-management-system"
version = "0.1.0"
description = "Product catalog and inventory management system"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
